/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2014-05-02 03:22:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class Awards_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ShowError.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Awards</title>\r\n");
      out.write("<link href=\"more.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" function changeTest() {\r\n");
      out.write("   \t    alert (\"Function is Called\");\t\t \r\n");
      out.write("\t \t\r\n");
      out.write("\t\tvar index = document.getElementById(\"rdown\").selectedIndex;\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar array1 = '");
      out.print( session.getAttribute( "rLastname" ) );
      out.write("';\r\n");
      out.write("\t\tvar array2 = '");
      out.print( session.getAttribute( "rName" ) );
      out.write("';\r\n");
      out.write("\t\tvar array3 = '");
      out.print( session.getAttribute( "rmailid" ) );
      out.write("';\r\n");
      out.write("\t\tvar array4 = '");
      out.print( session.getAttribute( "rdept" ) );
      out.write("';\r\n");
      out.write("\t\tvar array5 = '");
      out.print( session.getAttribute( "ruid" ) );
      out.write("';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar array1Token = array1.toString();\r\n");
      out.write("\t\tarray1Token = array1Token.slice(1, array1Token.length-1); \r\n");
      out.write("\t\tvar fields = array1Token.split(/,/);\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tvar array2Token = array2.toString();\r\n");
      out.write("\t\tarray2Token = array2Token.slice(1, array2Token.length-1); \r\n");
      out.write("\t\tvar fields2 = array2Token.split(/,/);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar array3Token = array3.toString();\r\n");
      out.write("\t\tarray3Token = array3Token.slice(1, array3Token.length-1); \r\n");
      out.write("\t\tvar fields3 = array3Token.split(/,/);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar array4Token = array4.toString();\r\n");
      out.write("\t\tarray4Token = array4Token.slice(1, array4Token.length-1); \r\n");
      out.write("\t\tvar fields4 = array4Token.split(/,/);\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\tvar array5Token = array5.toString();\r\n");
      out.write("\t\tarray5Token = array5Token.slice(1, array5Token.length-1); \r\n");
      out.write("\t\tvar fields5 = array5Token.split(/,/);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t if(parseInt(index) > 0 && parseInt(array1.length) > 0){\r\n");
      out.write("\t        \t\tdocument.getElementById('lr2').style.visibility='visible';\r\n");
      out.write("\t        \t\tdocument.getElementById('r2').style.visibility='visible';\r\n");
      out.write("\t        \t\tdocument.getElementById('r2').value = fields[index-1];\r\n");
      out.write("\t        \t\tdocument.getElementById('lr3').style.visibility='visible';\r\n");
      out.write("\t        \t\tdocument.getElementById('r3').style.visibility='visible';\r\n");
      out.write("\t        \t\tdocument.getElementById('r3').value = fields2[index-1];\r\n");
      out.write("\t        \t\tdocument.getElementById('lr4').style.visibility='visible';\r\n");
      out.write("\t        \t\tdocument.getElementById('r4').style.visibility='visible';\r\n");
      out.write("\t        \t\tdocument.getElementById('r4').value = fields3[index-1];\r\n");
      out.write("\t        \t\tdocument.getElementById('lr5').style.visibility='visible';\r\n");
      out.write("\t        \t\tdocument.getElementById('r5').style.visibility='visible';\r\n");
      out.write("\t        \t\tdocument.getElementById('r5').value = fields4[index-1];\r\n");
      out.write("\t        \t\tdocument.getElementById('lr6').style.visibility='visible';\r\n");
      out.write("\t        \t\tdocument.getElementById('rdownlist').style.visibility='visible';\r\n");
      out.write("\t        \t\tdocument.getElementById('lr7').style.visibility='visible';\r\n");
      out.write("\t        \t\tdocument.getElementById('r7').style.visibility='visible';\r\n");
      out.write("\t        \t\tdocument.getElementById('r8').value = fields5[index-1];\r\n");
      out.write("\t        \t}\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" function resetTest() {\r\n");
      out.write(" \t\t\t\t\tdocument.getElementById(\"rdown\").selectedIndex = -1;\r\n");
      out.write(" \t\t\t\t\tdocument.getElementById(\"r6\").selectedIndex = 0;\r\n");
      out.write(" \t\t\t\t\tdocument.getElementById('lr6').style.visibility='hidden';\r\n");
      out.write(" \t\t\t\t\tdocument.getElementById('rdownlist').style.visibility='hidden';\r\n");
      out.write(" \t\t\t\t\tdocument.getElementById('r7').style.visibility='hidden';\r\n");
      out.write(" \t\t\t\t\tdocument.getElementById('lr7').style.visibility='hidden';\r\n");
      out.write(" \t\t\t\t\tdocument.getElementById('lr2').style.visibility='hidden';\r\n");
      out.write("\t        \t\tdocument.getElementById('r2').style.visibility='hidden';\r\n");
      out.write("\t        \t\tdocument.getElementById('lr3').style.visibility='hidden';\r\n");
      out.write("\t        \t\tdocument.getElementById('r3').style.visibility='hidden';\r\n");
      out.write("\t        \t\tdocument.getElementById('lr4').style.visibility='hidden';\r\n");
      out.write("\t        \t\tdocument.getElementById('r4').style.visibility='hidden';\r\n");
      out.write("\t        \t\tdocument.getElementById('lr5').style.visibility='hidden';\r\n");
      out.write("\t        \t\tdocument.getElementById('r5').style.visibility='hidden';\r\n");
      out.write(" } \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form method=\"POST\" action=\"Awards\">\r\n");
      out.write("  <table width=\"page\" align=\"center\" >\r\n");
      out.write("  \t\t\t\t\t<tr>\r\n");
      out.write("  \t\t\t\t\t<td>Your Details</td>\r\n");
      out.write("  \t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t  <td height=\"40\" align=\"center\"> <label style=\"color:#ffffff;font-size:24px\" >First Name</label> </td>\r\n");
      out.write("             \t\t\t <td align=\"center\"> <input id=\"u1\" name=\"u1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.sfname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" type=\"text\" style =\"background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t  <td height=\"40\" align=\"center\"> <label style=\"color:#ffffff;font-size:24px\" >SurName</label> </td>\r\n");
      out.write("             \t\t\t <td align=\"center\"> <input id=\"u2\" name=\"u2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.ssname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" type=\"text\" style =\"background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t\t\t</tr>\r\n");
      out.write(" \t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t  <td height=\"40\" align=\"center\"> <label style=\"color:#ffffff;font-size:24px\" >Middle Name</label> </td>\r\n");
      out.write("             \t\t\t <td align=\"center\"> <input id=\"u3\" name=\"u3\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.slname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" type=\"text\" style =\"background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t\t\t</tr>\r\n");
      out.write(" \t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t  <td height=\"40\" align=\"center\"> <label style=\"color:#ffffff;font-size:24px\" >Email</label> </td>\r\n");
      out.write("             \t\t\t <td align=\"center\"> <input id=\"u4\" name=\"u4\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.smail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" type=\"text\" style =\"background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t\t\t</tr>\r\n");
      out.write(" \t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t  <td height=\"40\" align=\"center\"> <label style=\"color:#ffffff;font-size:24px\" >Dept ID</label> </td>\r\n");
      out.write("             \t\t\t <td align=\"center\"> <input id=\"u5\" name=\"u5\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.sdept}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" type=\"text\" style =\"background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t\t\t</tr>\r\n");
      out.write(" \t\t\t\t\t<tr>\r\n");
      out.write(" \t\t\t\t\t<td>Select Award Winner</td>\r\n");
      out.write(" \t\t\t\t\t</tr>\r\n");
      out.write(" \t\t\t\t\t<tr>\r\n");
      out.write(" \t\t\t\t\t\t\r\n");
      out.write(" \t\t\t\t\t\t <td height=\"40\" align=\"center\"> <label style=\"color:#ffffff;font-size:24px\" >First Name</label> </td>\r\n");
      out.write(" \t\t\t\t\t    <td>\r\n");
      out.write(" \t\t\t\t\t    <select name=\"rdown\" id=\"rdown\" onchange=\"changeTest()\">  \r\n");
      out.write("\t\t\t\t\t        <OPTION  value=\"-1\" label=\"--Select--\" selected=\"selected\">  \r\n");
      out.write("\t\t\t\t\t        ");
      if (_jspx_meth_core_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("\t\t\t\t\t    </select> \r\n");
      out.write("\t\t\t\t\t    </td>  \r\n");
      out.write("    \t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t  <td height=\"40\" align=\"center\"> <label id=\"lr2\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >SurName</label> </td>\r\n");
      out.write("             \t\t\t <td align=\"center\"> <input id=\"r2\" name=\"r2\" type=\"text\" style =\"visibility:hidden;background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t\t\t</tr>\r\n");
      out.write(" \t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t  <td height=\"40\" align=\"center\"> <label id=\"lr3\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Middle Name</label> </td>\r\n");
      out.write("             \t\t\t <td align=\"center\"> <input id=\"r3\" name=\"r3\" type=\"text\" style =\"background: #33CC99; visibility:hidden;height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t\t\t</tr>\r\n");
      out.write(" \t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t  <td height=\"40\" align=\"center\"> <label id=\"lr4\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Email</label> </td>\r\n");
      out.write("             \t\t\t <td align=\"center\"> <input id=\"r4\" name=\"r4\" type=\"text\" style =\"background: #33CC99; visibility:hidden;height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t\t\t</tr>\r\n");
      out.write(" \t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t  <td height=\"40\" align=\"center\"> <label id=\"lr5\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Dept ID</label> </td>\r\n");
      out.write("             \t\t\t <td align=\"center\"> <input id=\"r5\" name=\"r5\" type=\"text\" style =\"background: #33CC99; visibility:hidden;height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t\t\t</tr>\r\n");
      out.write(" \t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t  <td height=\"40\" align=\"center\"> <label id=\"lr6\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Select Award</label> </td>\r\n");
      out.write("             \t\t\t<td>\r\n");
      out.write(" \t\t\t\t\t    <select name=\"rdownlist\" id=\"rdownlist\" style=\"visibility:hidden;\">  \r\n");
      out.write("\t\t\t\t\t        <OPTION  value=\"-1\" label=\"--Select--\" selected=\"selected\">  \r\n");
      out.write("\t\t\t\t\t        ");
      if (_jspx_meth_core_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("\t\t\t\t\t    </select> \r\n");
      out.write("\t\t\t\t\t    </td>\r\n");
      out.write(" \t\t\t\t\t</tr>\r\n");
      out.write(" \t\t\t\t\t<tr>\r\n");
      out.write(" \t\t\t\t\t\t<td height=\"40\" align=\"center\"> <label id=\"lr7\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >You have made a difference..</label> </td>\r\n");
      out.write(" \t\t\t\t\t\t<td><textarea cols=\"50\" rows=\"5\" name=\"r7\" id=\"r7\" style=\"visibility:hidden;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"hidden\" name=\"r8\" id=\"r8\"></td>\r\n");
      out.write(" \t\t\t\t\t</tr>\r\n");
      out.write("  \t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\"><input type=\"submit\" name=\"Save\" value=\"Save\" style=\"background-color: #2e466e; color: #ffff; border-radius: 10px;border:6px solid #1f2f47;border-radius:29px;padding:16px 57px;text-shadow:0px 1px 0px #263666;font-size:20px;\">\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\"><input type=\"button\" name=\"Reset\" value=\"Reset\" onclick=\"resetTest()\" style=\"background-color: #2e466e; color: #ffff; border-radius: 10px;border:6px solid #1f2f47;border-radius:29px;padding:16px 57px;text-shadow:0px 1px 0px #263666;font-size:20px;\">\r\n");
      out.write("\t\t\t\t\t</tr>\t  \r\n");
      out.write("  </table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_core_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_core_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_core_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_core_005fforEach_005f0.setParent(null);
    // /Awards.jsp(120,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/Awards.jsp(120,13) '${sessionScope.rFname}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.rFname}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /Awards.jsp(120,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f0.setVar("dt");
    // /Awards.jsp(120,13) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f0.setVarStatus("status");
    int[] _jspx_push_body_count_core_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_core_005fforEach_005f0 = _jspx_th_core_005fforEach_005f0.doStartTag();
      if (_jspx_eval_core_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \r\n");
          out.write("\t\t\t\t\t            <option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option> \r\n");
          out.write("\t\t\t\t\t        ");
          int evalDoAfterBody = _jspx_th_core_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_core_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_core_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_core_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_core_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_core_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_core_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_core_005fforEach_005f1.setParent(null);
    // /Awards.jsp(147,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/Awards.jsp(147,13) '${sessionScope.awardList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.awardList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /Awards.jsp(147,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f1.setVar("dt");
    // /Awards.jsp(147,13) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f1.setVarStatus("status");
    int[] _jspx_push_body_count_core_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_core_005fforEach_005f1 = _jspx_th_core_005fforEach_005f1.doStartTag();
      if (_jspx_eval_core_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \r\n");
          out.write("\t\t\t\t\t            <option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option> \r\n");
          out.write("\t\t\t\t\t        ");
          int evalDoAfterBody = _jspx_th_core_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_core_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_core_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_core_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_core_005fforEach_005f1);
    }
    return false;
  }
}
