/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2014-05-04 17:59:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;

public final class entranceAdminFunction_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ShowError.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Edit Award</title>\r\n");
      out.write("<link href=\"more.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function checkDate(varBirthDate) {\r\n");
      out.write("\r\n");
      out.write("            var month = varBirthDate.substring(0, 2);\r\n");
      out.write("            var date = varBirthDate.substring(3, 5);\r\n");
      out.write("            var year = varBirthDate.substring(6, 10);\r\n");
      out.write("\r\n");
      out.write("\t\t\tif(parseInt(month) < 1 || parseInt(month) > 12){\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t}else if(parseInt(date) < 1 || parseInt(date) > 31){\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t}else if(parseInt(year) < 1900 || parseInt(year) > 2014){\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("            var myDate = new Date(year, month - 1, date);\r\n");
      out.write("\r\n");
      out.write("            var today = new Date();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("            if (myDate > today) {\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("                return true;\r\n");
      out.write("            }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checktwoDate(vartoolcountDate,vartoolcountDate1) {\r\n");
      out.write("            var month = vartoolcountDate.substring(0, 2);\r\n");
      out.write("            var date = vartoolcountDate.substring(3, 5);\r\n");
      out.write("            var year = vartoolcountDate.substring(6, 10);\r\n");
      out.write("            var myDate = new Date(year, month - 1, date);\r\n");
      out.write("            \r\n");
      out.write("            var month1 = vartoolcountDate1.substring(0, 2);\r\n");
      out.write("            var date1 = vartoolcountDate1.substring(3, 5);\r\n");
      out.write("            var year1 = vartoolcountDate1.substring(6, 10);\r\n");
      out.write("            var myDate1 = new Date(year1, month1 - 1, date1);\r\n");
      out.write("            \r\n");
      out.write("            if (myDate > myDate1) {\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("                return true;\r\n");
      out.write("            }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validateform5() {\r\n");
      out.write("\t\tvar varBirthDate = /^(\\d{2,2})(\\/)(\\d{2,2})\\2(\\d{4}|\\d{4})$/;\r\n");
      out.write("\t\tif(!(varBirthDate.test(document.getElementById(\"r5\").value) && checkDate(document.getElementById(\"r5\").value)))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Please enter a valid birth date MM/DD/YYYY and Date Not Greater Than Today.\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"r5\").select();\r\n");
      out.write("\t\t\tdocument.getElementById(\"r5\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById('lr6').style.visibility='visible';\r\n");
      out.write("\t\tdocument.getElementById('r6').style.visibility='visible';\r\n");
      out.write("}\r\n");
      out.write("function validateformd9() {\r\n");
      out.write("\t\tvar varBirthDate = /^(\\d{2,2})(\\/)(\\d{2,2})\\2(\\d{4}|\\d{4})$/;\r\n");
      out.write("\t\tif(!(varBirthDate.test(document.getElementById(\"r6\").value) && checkDate(document.getElementById(\"r6\").value)))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Please enter a valid birth date MM/DD/YYYY and Date Not Greater Than Today.\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"r6\").select();\r\n");
      out.write("\t\t\tdocument.getElementById(\"r6\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!checktwoDate(document.getElementById(\"r5\").value,document.getElementById(\"r6\").value)){\r\n");
      out.write("\t\t\talert(\"Start Date Should Be less than End Date\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"r6\").select();\r\n");
      out.write("\t\t\tdocument.getElementById(\"r6\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById('change').style.visibility='visible';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validateform4() {\r\n");
      out.write("\t\t\tvar varCity = /^[a-zA-Z\\s]*$/;\r\n");
      out.write("\t\t\tif(!(varCity.test(document.getElementById(\"r4\").value)))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Please enter a valid Name, Name can only contain alphabets\");\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"r4\").select();\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"r4\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('lr5').style.visibility='visible';\r\n");
      out.write("\t\t\tdocument.getElementById('r5').style.visibility='visible';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validateform7() {\r\n");
      out.write("\t\t\tre = /^\\d+$/; \r\n");
      out.write("\t\t\t\tif(!re.test(document.getElementById(\"r7\").value) && (document.getElementById(\"r7\").value < 1))\r\n");
      out.write("\t\t\t\t{ \r\n");
      out.write("\t\t\t\t\talert(\"Error: password must contain at least one number (0-9)! and min 1\"); \r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"r7\").select();\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"r7\").focus();\r\n");
      out.write("\t\t\t\t\treturn false; \r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\tdocument.getElementById('change').style.visibility='visible';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function validateform32() {\r\n");
      out.write("\t\t\tre = /^\\d+$/; \r\n");
      out.write("\t\t\t\tif(!re.test(document.getElementById(\"r32\").value) && (document.getElementById(\"r32\").value < 1))\r\n");
      out.write("\t\t\t\t{ \r\n");
      out.write("\t\t\t\t\talert(\"Error: password must contain at least one number (0-9)! and min 1\"); \r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"r32\").select();\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"r32\").focus();\r\n");
      out.write("\t\t\t\t\treturn false; \r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("}\r\n");
      out.write("function validateform31() {\r\n");
      out.write("\t\t\tvar varCity = /^[a-zA-Z\\s]*$/;\r\n");
      out.write("\t\t\tif(!(varCity.test(document.getElementById(\"r31\").value)))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Please enter a valid Name, Name can only contain alphabets\");\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"r31\").select();\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"r31\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('lr32').style.visibility='visible';\r\n");
      out.write("    \t\tdocument.getElementById('r32').style.visibility='visible';\r\n");
      out.write("    \t\tdocument.getElementById('lr33').style.visibility='visible';\r\n");
      out.write("    \t\tdocument.getElementById('r33').style.visibility='visible';\r\n");
      out.write("}\r\n");
      out.write("function changeTest2() {\r\n");
      out.write("\tvar index = document.getElementById(\"r2\").selectedIndex;\r\n");
      out.write("\tif(parseInt(index) == 1){\r\n");
      out.write("\t\tdocument.getElementById('lr31').style.visibility='visible';\r\n");
      out.write("    \tdocument.getElementById('r31').style.visibility='visible';\r\n");
      out.write("    \tdocument.getElementById('lr3').style.visibility='hidden';\r\n");
      out.write("    \tdocument.getElementById('r3').style.visibility='hidden';\r\n");
      out.write("\t\tdocument.getElementById('lr32').style.visibility='hidden';\r\n");
      out.write("    \tdocument.getElementById('r32').style.visibility='hidden';\r\n");
      out.write("    \tdocument.getElementById('lr33').style.visibility='hidden';\r\n");
      out.write("    \tdocument.getElementById('r33').style.visibility='hidden';\r\n");
      out.write("\t}else if(parseInt(index) == 2){\r\n");
      out.write("\t\tdocument.getElementById('lr31').style.visibility='hidden';\r\n");
      out.write("    \tdocument.getElementById('r31').style.visibility='hidden';\r\n");
      out.write("\t\tdocument.getElementById('lr3').style.visibility='visible';\r\n");
      out.write("    \tdocument.getElementById('r3').style.visibility='visible';\r\n");
      out.write("\t\tdocument.getElementById('lr32').style.visibility='hidden';\r\n");
      out.write("    \tdocument.getElementById('r32').style.visibility='hidden';\r\n");
      out.write("    \tdocument.getElementById('lr33').style.visibility='hidden';\r\n");
      out.write("    \tdocument.getElementById('r33').style.visibility='hidden';\r\n");
      out.write("    \tdocument.getElementById('change').style.visibility='visible';\r\n");
      out.write("\t}else if(parseInt(index) == 3){\r\n");
      out.write("\t\tdocument.getElementById('lr31').style.visibility='hidden';\r\n");
      out.write("    \tdocument.getElementById('r31').style.visibility='hidden';\r\n");
      out.write("\t\tdocument.getElementById('lr3').style.visibility='visible';\r\n");
      out.write("    \tdocument.getElementById('r3').style.visibility='visible';\r\n");
      out.write("\t\tdocument.getElementById('lr32').style.visibility='hidden';\r\n");
      out.write("    \tdocument.getElementById('r32').style.visibility='hidden';\r\n");
      out.write("    \tdocument.getElementById('lr33').style.visibility='visible';\r\n");
      out.write("    \tdocument.getElementById('r33').style.visibility='visible';\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(parseInt(index) == 4){\r\n");
      out.write("\t\tdocument.getElementById('lr31').style.visibility='hidden';\r\n");
      out.write("    \tdocument.getElementById('r31').style.visibility='hidden';\r\n");
      out.write("\t\tdocument.getElementById('lr3').style.visibility='visible';\r\n");
      out.write("    \tdocument.getElementById('r3').style.visibility='visible';\r\n");
      out.write("    \tdocument.getElementById('lr32').style.visibility='visible';\r\n");
      out.write("    \tdocument.getElementById('r32').style.visibility='visible';\r\n");
      out.write("\t\tdocument.getElementById('lr33').style.visibility='hidden';\r\n");
      out.write("    \tdocument.getElementById('r33').style.visibility='hidden';\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function changeTest33(){\r\n");
      out.write("\tvar index = document.getElementById(\"r33\").selectedIndex;\r\n");
      out.write("\tif(parseInt(index) == 1){\r\n");
      out.write("\t\tdocument.getElementById('change').style.visibility='visible';\r\n");
      out.write(" \t}else if(parseInt(index) == 2){\r\n");
      out.write("\t\tdocument.getElementById('change').style.visibility='visible';\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function changeTest12() {\r\n");
      out.write("\tvar index = document.getElementById(\"r12\").selectedIndex;\r\n");
      out.write("\tif(parseInt(index) == 1){\r\n");
      out.write("\t\tdocument.getElementById('change').style.visibility='visible';\r\n");
      out.write("\t}else if(parseInt(index) == 2){\r\n");
      out.write("\t\tdocument.getElementById('change').style.visibility='visible';\r\n");
      out.write("\t}else if(parseInt(index) == 3){\r\n");
      out.write("\t\tdocument.getElementById('change').style.visibility='visible';\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function validateform11(){\r\n");
      out.write("\tvar varCity = /^[a-zA-Z]*$/;\r\n");
      out.write("\t\t\tif(!(varCity.test(document.getElementById(\"r11\").value)))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Please enter a valid Name, Name can only contain alphabets\");\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"r11\").select();\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"r11\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('lr12').style.visibility='visible';\r\n");
      out.write("    \t\tdocument.getElementById('r12').style.visibility='visible';\r\n");
      out.write("}\r\n");
      out.write("function changeTest1(){\r\n");
      out.write("\tvar index = document.getElementById(\"r1\").selectedIndex;\r\n");
      out.write("\tif(parseInt(index) == 1){\r\n");
      out.write("\t\tdocument.getElementById('lr11').style.visibility='visible';\r\n");
      out.write("    \t\tdocument.getElementById('r11').style.visibility='visible';\r\n");
      out.write("\t}else if(parseInt(index) == 2){\r\n");
      out.write("\t\tdocument.getElementById('lr11').style.visibility='visible';\r\n");
      out.write("    \t\tdocument.getElementById('r11').style.visibility='visible';\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write(" function changeTest() {\r\n");
      out.write("   \t \t\r\n");
      out.write("\tvar index = document.getElementById(\"rdown\").selectedIndex;\r\n");
      out.write("\tdocument.getElementById(\"r1\").selectedIndex = 0;\r\n");
      out.write("\tdocument.getElementById(\"r12\").selectedIndex = 0;\r\n");
      out.write("\tdocument.getElementById(\"r2\").selectedIndex = 0;\r\n");
      out.write("\tdocument.getElementById(\"r3\").selectedIndex = 0;\r\n");
      out.write("\t\r\n");
      out.write("\t");
 
	try{
			Class.forName ("com.mysql.jdbc.jdbc2.optional.MysqlDataSource").newInstance();
			
			Class.forName("com.mysql.jdbc.Driver").newInstance(); 
			Connection con = DriverManager.getConnection("jdbc:mysql://bigyellowcat.cs.binghamton.edu/more", "more", "more7755");
			
		    // Create statement
		    Statement stmt = con.createStatement();
		    
			String query1 = "SELECT * FROM AwardList WHERE status='ACTIVE' AND AwardCount > 1";
		    // Execute the query
		    ResultSet rs1 = stmt.executeQuery(query1);
		  
		    	ArrayList<String>  aawardname =  new ArrayList<String>();
		    	
		    	while(rs1.next())
			      {
			          String str1 = rs1.getString("AwardName");
			          aawardname.add(str1);
			      }
			      session.setAttribute("aawardname", aawardname);
		}catch (SQLException e) {
			out.print("Error on authentication: " + e.toString());
			RequestDispatcher rd = request
					.getRequestDispatcher("./entranceAdminFunction.jsp");
			rd.include(request, response);
		}
	
      out.write("\r\n");
      out.write("\t\t if(parseInt(index) == 1){\r\n");
      out.write("       \t\tdocument.getElementById('lr1').style.visibility='visible';\r\n");
      out.write("    \t\tdocument.getElementById('r1').style.visibility='visible';\r\n");
      out.write("    \t\tdocument.getElementById('lr2').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r2').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr4').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r4').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr7').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r7').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr11').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r11').style.visibility='hidden';\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tdocument.getElementById('change').style.visibility='hidden';\r\n");
      out.write("    \t\t\r\n");
      out.write("       \t}else  if(parseInt(index) == 2){\r\n");
      out.write("       \t\tdocument.getElementById('lr1').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r1').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr2').style.visibility='visible';\r\n");
      out.write("    \t\tdocument.getElementById('r2').style.visibility='visible';\r\n");
      out.write("    \t\tdocument.getElementById('lr3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr4').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r4').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr7').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r7').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr11').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r11').style.visibility='hidden';\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tdocument.getElementById('change').style.visibility='hidden';\r\n");
      out.write("       \t}else  if(parseInt(index) == 3){\r\n");
      out.write("       \t\tdocument.getElementById('lr1').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r1').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr2').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r2').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr4').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r4').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr7').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r7').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr11').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r11').style.visibility='hidden';\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tdocument.getElementById('change').style.visibility='hidden';\r\n");
      out.write("       \t}else  if(parseInt(index) == 4){\r\n");
      out.write("       \t\tdocument.getElementById('lr1').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r1').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr2').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r2').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr4').style.visibility='visible';\r\n");
      out.write("    \t\tdocument.getElementById('r4').style.visibility='visible';\r\n");
      out.write("    \t\tdocument.getElementById('lr5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr7').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r7').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr11').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r11').style.visibility='hidden';\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tdocument.getElementById('change').style.visibility='hidden';\r\n");
      out.write("       \t}else  if(parseInt(index) == 5){\r\n");
      out.write("       \t\tdocument.getElementById('lr1').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r1').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr2').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r2').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr4').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r4').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr7').style.visibility='visible';\r\n");
      out.write("    \t\tdocument.getElementById('r7').style.visibility='visible';\r\n");
      out.write("    \t\tdocument.getElementById('lr12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr11').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r11').style.visibility='hidden';\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tdocument.getElementById('change').style.visibility='hidden';\r\n");
      out.write("       \t}else  if(parseInt(index) == 6){\r\n");
      out.write("       \t\tdocument.getElementById('lr1').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r1').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr2').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r2').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr4').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r4').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr7').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r7').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr11').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r11').style.visibility='hidden';\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tdocument.getElementById('change').style.visibility='visible';\r\n");
      out.write("       \t}else  if(parseInt(index) == 7){\r\n");
      out.write("       \t\tdocument.getElementById('lr1').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r1').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr2').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r2').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr4').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r4').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr7').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r7').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr11').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r11').style.visibility='hidden';\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tdocument.getElementById('change').style.visibility='visible';\r\n");
      out.write("       \t}else  if(parseInt(index) == 8){\r\n");
      out.write("       \t\tdocument.getElementById('lr1').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r1').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr2').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r2').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r3').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr4').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r4').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r5').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r6').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr7').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r7').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r12').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r31').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r32').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('lr11').style.visibility='hidden';\r\n");
      out.write("    \t\tdocument.getElementById('r11').style.visibility='hidden';\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tdocument.getElementById('change').style.visibility='visible';\r\n");
      out.write("       \t}\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\t\r\n");
      out.write("<form method=\"POST\" action=\"EntranceAdminFunction\">\r\n");
      out.write("<br><input type=\"text\" readonly=\"readonly\" name=\"username\" id=\"username\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" style =\"background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <table width=\"page\" align=\"center\" >\r\n");
      out.write("  \t\t\t<tr>\r\n");
      out.write(" \t\t\t\t\t\t\r\n");
      out.write(" \t\t\t\t\t\t <td height=\"40\" align=\"center\"> <label style=\"color:#ffffff;font-size:24px\" >Select Report Search</label> </td>\r\n");
      out.write(" \t\t\t\t\t    <td>\r\n");
      out.write(" \t\t\t\t\t    <select name=\"rdown\" id=\"rdown\" onchange=\"changeTest()\">  \r\n");
      out.write("\t\t\t\t\t        <OPTION  value=\"-1\" label=\"--Select--\" selected=\"selected\">  \r\n");
      out.write("\t\t\t\t\t        <option value=\"AccessControl\">Award Control</option>\r\n");
      out.write("\t\t\t\t\t        <option value=\"AwardData\">Award Data</option>\r\n");
      out.write("\t\t\t\t\t        <option value=\"TQMCertificate\">TQM Category</option>\r\n");
      out.write("\t\t\t\t\t        <option value=\"News\">News</option>\r\n");
      out.write("\t\t\t\t\t        <option value=\"ChangeMax\">Change Max Submissions</option>\r\n");
      out.write("\t\t\t\t\t        <option value=\"Searchdrop\">Search</option>\r\n");
      out.write("\t\t\t\t\t        <option value=\"DeleteOld\">Delete Old Data</option>\r\n");
      out.write("\t\t\t\t\t        <option value=\"Waiting\">Waiting for Approval</option>\r\n");
      out.write("\t\t\t\t\t    </select> \r\n");
      out.write("\t\t\t\t\t    </td>  \r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("    \t\t<!-- Access Control -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr1\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Please Select Access Control</label> </td>\r\n");
      out.write("             \t\t <td align=\"center\"> \r\n");
      out.write("             \t\t <td>\r\n");
      out.write(" \t\t\t\t\t    <select name=\"r1\" id=\"r1\" onchange=\"changeTest1()\" style=\"visibility:hidden;\">  \r\n");
      out.write("\t\t\t\t\t        <OPTION  value=\"-1\" label=\"--Select--\" selected=\"selected\">  \r\n");
      out.write("\t\t\t\t\t        <option value=\"Add\">Add</option>\r\n");
      out.write("\t\t\t\t\t        <option value=\"Delete\">Delete</option>\r\n");
      out.write("\t\t\t\t\t     </select> \r\n");
      out.write("\t\t\t\t\t    </td>  \r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr11\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Enter uid</label> </td>\r\n");
      out.write("             \t\t <td align=\"center\"> <input id=\"r11\" name=\"r11\" onchange=\"validateform11()\" type=\"text\" style =\"visibility:hidden;background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr12\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Select Access Type</label> </td>\r\n");
      out.write("             \t\t <td>\r\n");
      out.write(" \t\t\t\t\t    <select name=\"r12\" id=\"r12\" onchange=\"changeTest12()\" style=\"visibility:hidden;\">  \r\n");
      out.write("\t\t\t\t\t        <OPTION  value=\"-1\" label=\"--Select--\" selected=\"selected\">  \r\n");
      out.write("\t\t\t\t\t        <option value=\"Manager\">Manager</option>\r\n");
      out.write("\t\t\t\t\t        <option value=\"Administrator\">Administrator</option>\r\n");
      out.write("\t\t\t\t\t        <option value=\"AdministratorManager\">AdministratorManager</option>\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t     </select> \r\n");
      out.write("\t\t\t\t\t    </td>\r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t<!-- Award Data -->\r\n");
      out.write(" \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr2\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Award Data</label> </td>\r\n");
      out.write("             \t\t <td>\r\n");
      out.write(" \t\t\t\t\t    <select name=\"r2\" id=\"r2\" onchange=\"changeTest2()\" style=\"visibility:hidden;\">  \r\n");
      out.write("\t\t\t\t\t        <OPTION  value=\"-1\" label=\"--Select--\" selected=\"selected\">  \r\n");
      out.write("\t\t\t\t\t        <option value=\"Add\">Add Award</option>\r\n");
      out.write("\t\t\t\t\t        <option value=\"Delete\">Delete Award</option>\r\n");
      out.write("\t\t\t\t\t        <option value=\"ChangeS\">Change Status</option>\r\n");
      out.write("\t\t\t\t\t        <option value=\"ChangeC\">Change Count</option>\r\n");
      out.write("\t\t\t\t\t     </select> \r\n");
      out.write("\t\t\t\t\t    </td>\r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr3\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Select Award to Delete/Change Status</label> </td>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t <td>\r\n");
      out.write(" \t\t\t\t\t    <select name=\"r3\" id=\"r3\" style=\"visibility:hidden;\">  \r\n");
      out.write("\t\t\t\t\t        <OPTION  value=\"-1\" label=\"--Select--\" selected=\"selected\">  \r\n");
      out.write("\t\t\t\t\t        ");
      if (_jspx_meth_core_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("\t\t\t\t\t    </select> \r\n");
      out.write("\t\t\t\t\t    </td>   \r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr31\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Enter New Award</label> </td>\r\n");
      out.write("             \t\t <td align=\"center\"> <input id=\"r31\" name=\"r31\" onchange=\"validateform31()\" type=\"text\" style =\"visibility:hidden;background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr32\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Enter Award Count</label> </td>\r\n");
      out.write("             \t\t <td align=\"center\"> <input id=\"r32\" name=\"r32\" onchange=\"validateform32()\" type=\"text\" style =\"visibility:hidden;background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td height=\"40\" align=\"center\"> <label id=\"lr33\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Select Status</label> </td>\r\n");
      out.write("             \t\t <td>\r\n");
      out.write(" \t\t\t\t\t    <select name=\"r33\" id=\"r33\" onchange=\"changeTest33()\" style=\"visibility:hidden;\">  \r\n");
      out.write("\t\t\t\t\t        <OPTION  value=\"-1\" label=\"--Select--\" selected=\"selected\">  \r\n");
      out.write("\t\t\t\t\t        <option value=\"ACTIVE\">ACTIVE</option>\r\n");
      out.write("\t\t\t\t\t        <option value=\"INACTIVE\">INACTIVE</option>\r\n");
      out.write("\t\t\t\t\t     </select> \r\n");
      out.write("\t\t\t\t\t    </td>\r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t<!-- News -->\r\n");
      out.write(" \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr4\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Enter News</label> </td>\r\n");
      out.write("             \t\t <td align=\"center\"> <input id=\"r4\" name=\"r4\" onchange=\"validateform4()\" type=\"text\" style =\"visibility:hidden;background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr5\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Enter To Date</label> </td>\r\n");
      out.write("             \t\t <td align=\"center\"> <input id=\"r5\" name=\"r5\" onchange=\"validateform5()\" type=\"text\" style =\"visibility:hidden;background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr6\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Enter From Date</label> </td>\r\n");
      out.write("             \t\t <td align=\"center\"> <input id=\"r6\" name=\"r6\" onchange=\"validateformd9()\" type=\"text\" style =\"visibility:hidden;background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\t<!-- Enter Max Submissions -->\r\n");
      out.write(" \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr7\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Enter Maximum Submission</label> </td>\r\n");
      out.write("             \t\t <td align=\"center\"> <input id=\"r7\" name=\"r7\" onchange=\"validateform7()\" type=\"text\" style =\"visibility:hidden;background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t\r\n");
      out.write("  \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\"><input type=\"submit\" name=\"change\" id=\"change\" value=\"change\" style=\"visibility:hidden;background-color: #2e466e; color: #ffff; border-radius: 10px;border:6px solid #1f2f47;border-radius:29px;padding:16px 57px;text-shadow:0px 1px 0px #263666;font-size:20px;\">\r\n");
      out.write("\t\t\t</tr>\t  \r\n");
      out.write(" </table>\r\n");
      out.write(" </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_core_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_core_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_core_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_core_005fforEach_005f0.setParent(null);
    // /entranceAdminFunction.jsp(538,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/entranceAdminFunction.jsp(538,13) '${sessionScope.aawardname}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.aawardname}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /entranceAdminFunction.jsp(538,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f0.setVar("dt");
    // /entranceAdminFunction.jsp(538,13) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f0.setVarStatus("status");
    int[] _jspx_push_body_count_core_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_core_005fforEach_005f0 = _jspx_th_core_005fforEach_005f0.doStartTag();
      if (_jspx_eval_core_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \r\n");
          out.write("\t\t\t\t\t            <option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option> \r\n");
          out.write("\t\t\t\t\t        ");
          int evalDoAfterBody = _jspx_th_core_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_core_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_core_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_core_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_core_005fforEach_005f0);
    }
    return false;
  }
}
