/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2014-05-04 08:05:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class entranceAwardWinners_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ShowError.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Awards</title>\r\n");
      out.write("<link href=\"more.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var myArray = new Array();\r\n");
      out.write("var loc = -1;\r\n");
      out.write("var insertflag1;\r\n");
      out.write("\r\n");
      out.write("var upstatus;\r\n");
      out.write("function successCallback(){\r\n");
      out.write("  \tvar name = '");
      out.print( session.getAttribute( "award" ) );
      out.write("';\r\n");
      out.write("\tvar details = '");
      out.print( session.getAttribute( "details" ) );
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tvar array1Token = name.toString();\r\n");
      out.write("\t\tarray1Token = array1Token.slice(1, array1Token.length-1); \r\n");
      out.write("\t\tvar fields = array1Token.split(/,/);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar array2Token = details.toString();\r\n");
      out.write("\t\tarray2Token = array2Token.slice(1, array2Token.length-1); \r\n");
      out.write("\t\tvar fields2 = array2Token.split(/,/);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tloc = -1;\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\tfor (var i = 0; i < 3 ; i++) {\r\n");
      out.write("\t\t\t\t\tvar num = i + 1;\r\n");
      out.write("\t\t\t\t\tvar n = num.toString(); \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar name = \"name\".concat(n);\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(name).value = \"\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar sssn = \"detail\".concat(n);\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(sssn).value = \"\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar pos = \"pos\".concat(n);\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(pos).value = \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\tfor (var i = 0; i < fields.length ; i++) {\r\n");
      out.write("\t\t\t\t\tif(i >= 3) {\r\n");
      out.write("\t\t\t\t\t\tloc = loc + 1;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"name1\").value = fields[i-2];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"detail1\").value = fields2[i-2];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"pos1\").value = i-2;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"name2\").value = fields[i-1];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"detail2\").value = fields2[i-1];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"pos2\").value = i-1;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"name3\").value = fields[i];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"detail3\").value = fields2[i];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"pos3\").value = i;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tloc = loc + 1;\r\n");
      out.write("\t\t\t\t\t\t\tvar num = i + 1;\r\n");
      out.write("\t\t\t\t\t\t\tvar n = num.toString(); \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tvar name = \"name\".concat(n);\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(name).value = fields[i];\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tvar sssn = \"detail\".concat(n);\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(sssn).value = fields2[i];\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tvar pos = \"pos\".concat(n);\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(pos).value = i;\r\n");
      out.write("\t\t\t\t\t\t\talert(pos);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function scrollDown()\r\n");
      out.write("{\t\r\n");
      out.write("\t\tvar scrollstatus = document.getElementById(\"pos1\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar name = '");
      out.print( session.getAttribute( "award" ) );
      out.write("';\r\n");
      out.write("\t\tvar details = '");
      out.print( session.getAttribute( "details" ) );
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar array1Token = name.toString();\r\n");
      out.write("\t\tarray1Token = array1Token.slice(1, array1Token.length-1); \r\n");
      out.write("\t\tvar fields = array1Token.split(/,/);\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tvar array2Token = details.toString();\r\n");
      out.write("\t\tarray2Token = array2Token.slice(1, array2Token.length-1); \r\n");
      out.write("\t\tvar fields2 = array2Token.split(/,/);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tloc = -1;\r\n");
      out.write("\t\t\r\n");
      out.write("\tif(fields.length < 3 || (parseInt(parseInt(scrollstatus) + 3))== fields.length){\r\n");
      out.write("\t\t\talert(\"Cannot scroll down\");\r\n");
      out.write("\t}else {\r\n");
      out.write(" \t\tfor (var i = 0; i < 3 ; i++) {\r\n");
      out.write("\t\t\t\t\tvar num = i + 1;\r\n");
      out.write("\t\t\t\t\tvar n = num.toString(); \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar name = \"name\".concat(n);\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(name).value = \"\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar sssn = \"detail\".concat(n);\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(sssn).value = \"\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar pos = \"pos\".concat(n);\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(pos).value = \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar i = parseInt(parseInt(scrollstatus));\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"name1\").value = fields[i+1];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"detail1\").value = fields2[i+1];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"pos1\").value = i+1;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"name2\").value = fields[i+2];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"detail2\").value = fields2[i+2];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"pos2\").value = i+2;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"name3\").value = fields[i+3];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"detail3\").value = fields2[i+3];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"pos3\").value = i+3;\t\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function scrollUp()\r\n");
      out.write("{\r\n");
      out.write("\t\tvar scrollstatus = document.getElementById(\"pos3\").value;\r\n");
      out.write("\t\tvar name = '");
      out.print( session.getAttribute( "award" ) );
      out.write("';\r\n");
      out.write("\t\tvar details = '");
      out.print( session.getAttribute( "details" ) );
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar array1Token = name.toString();\r\n");
      out.write("\t\tarray1Token = array1Token.slice(1, array1Token.length-1); \r\n");
      out.write("\t\tvar fields = array1Token.split(/,/);\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tvar array2Token = details.toString();\r\n");
      out.write("\t\tarray2Token = array2Token.slice(1, array2Token.length-1); \r\n");
      out.write("\t\tvar fields2 = array2Token.split(/,/);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tloc = -1;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(fields.length < 3 || (parseInt(parseInt(scrollstatus) - 3)) < 0){\r\n");
      out.write("\t\t\t\talert(\"Cannot scroll up\");\r\n");
      out.write("\t\t}else {\r\n");
      out.write("\t \t\tfor (var i = 0; i < 3 ; i++) {\r\n");
      out.write("\t\t\t\t\tvar num = i + 1;\r\n");
      out.write("\t\t\t\t\tvar n = num.toString(); \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar name = \"name\".concat(n);\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(name).value = \"\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar sssn = \"detail\".concat(n);\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(sssn).value = \"\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar pos = \"pos\".concat(n);\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(pos).value = \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar i = parseInt(parseInt(scrollstatus));\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"name1\").value = fields[i-3];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"detail1\").value = fields2[i-3];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"pos1\").value = i-3;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"name2\").value = fields[i-2];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"detail2\").value = fields2[i-2];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"pos2\").value = i-2;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"name3\").value = fields[i-1];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"detail3\").value = fields2[i-1];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"pos3\").value = i-1;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body  onload=\"successCallback()\">\r\n");
      out.write("\t\t<h1>Award Form</h1>\r\n");
      out.write("\t\t\t<form name=\"myForm\"  method=\"POST\" action=\"entranceAwardWinners\">\r\n");
      out.write("\t\t\t\t<table width=\"page\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">Award</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">Details</td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"submit\" name=\"sub\" id=\"sub1\" value=\"Select1\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"name1\" type=\"text\" name=\"name1\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"detail1\" type=\"text\" name=\"detail\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"button\" name=\"up\" value=\"Scroll Up\" onClick=\"scrollUp()\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"pos1\" type=\"hidden\" readonly></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"submit\" name=\"sub\" id=\"sub2\" value=\"Select2\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"name2\" type=\"text\" name=\"name2\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"detail2\" type=\"text\" name=\"detail\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"pos2\" type=\"hidden\" readonly></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"submit\" name=\"sub\" id=\"sub3\" value=\"Select3\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"name3\" type=\"text\" name=\"name3\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"detail3\" type=\"text\" name=\"detail\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"button\" name=\"down\" value=\"Scroll Down\" onClick=\"scrollDown()\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"pos3\" type=\"hidden\" readonly></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
