/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2014-05-03 06:44:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class finalAdminReport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ShowError.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Edit Award</title>\r\n");
      out.write("<link href=\"more.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" function validateform() {\r\n");
      out.write(" var index = document.getElementById(\"r8\").selectedIndex;\r\n");
      out.write("\tdocument.getElementById(\"r3\").selectedIndex = 0;\r\n");
      out.write("\t\r\n");
      out.write("\t\t if(parseInt(index) == 1){\r\n");
      out.write("\t\t\tdocument.getElementById('lr1').style.visibility='visible';\r\n");
      out.write("\t\t\tdocument.getElementById('r1').style.visibility='visible';\r\n");
      out.write("\t\t\tdocument.getElementById('lr2').style.visibility='hidden';\r\n");
      out.write("\t\t\tdocument.getElementById('r2').style.visibility='hidden';\r\n");
      out.write("\t\t\tdocument.getElementById('lr3').style.visibility='hidden';\r\n");
      out.write("\t\t\tdocument.getElementById('r3').style.visibility='hidden';\r\n");
      out.write("\t\t\tdocument.getElementById('Delete').style.visibility='hidden';\r\n");
      out.write("\t\t\tdocument.getElementById('update').style.visibility='hidden';\r\n");
      out.write("\t\t\tdocument.getElementById('lr4').style.visibility='hidden';\r\n");
      out.write("\t\tdocument.getElementById('r4').style.visibility='hidden';\r\n");
      out.write("\t\t }else if(parseInt(index) == 2){\r\n");
      out.write("\t\t \tdocument.getElementById('lr1').style.visibility='visible';\r\n");
      out.write("\t\t\tdocument.getElementById('r1').style.visibility='visible';\r\n");
      out.write("\t\t\tdocument.getElementById('lr2').style.visibility='hidden';\r\n");
      out.write("\t\t\tdocument.getElementById('r2').style.visibility='hidden';\r\n");
      out.write("\t\t\tdocument.getElementById('lr3').style.visibility='hidden';\r\n");
      out.write("\t\t\tdocument.getElementById('r3').style.visibility='hidden';\r\n");
      out.write("\t\t\tdocument.getElementById('Delete').style.visibility='hidden';\r\n");
      out.write("\t\t\tdocument.getElementById('update').style.visibility='hidden';\r\n");
      out.write("\t\t\tdocument.getElementById('lr4').style.visibility='hidden';\r\n");
      out.write("\t\tdocument.getElementById('r4').style.visibility='hidden';\r\n");
      out.write("\t\t }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validateform1() {\r\n");
      out.write("\t\t\tvar varCity = /^[a-zA-Z]*$/;\r\n");
      out.write("\t\t\tif(!(varCity.test(document.getElementById(\"r1\").value)))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Please enter a valid Name, Name can only contain alphabets\");\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"r1\").select();\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"r1\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('lr2').style.visibility='visible';\r\n");
      out.write("\t\t\tdocument.getElementById('r2').style.visibility='visible';\r\n");
      out.write("}\r\n");
      out.write("function validateform2() {\r\n");
      out.write("\t\t\tvar varCity = /^[a-zA-Z]*$/;\r\n");
      out.write("\t\t\tif(!(varCity.test(document.getElementById(\"r2\").value)))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Please enter a valid Name, Name can only contain alphabets\");\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"r2\").select();\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"r2\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('lr3').style.visibility='visible';\r\n");
      out.write("\t\t\tdocument.getElementById('r3').style.visibility='visible';\r\n");
      out.write("}\r\n");
      out.write("function validateform3() {\r\n");
      out.write("\tvar index = document.getElementById(\"r3\").selectedIndex;\r\n");
      out.write("\tvar index1 = document.getElementById(\"r8\").selectedIndex;\r\n");
      out.write("\tif(index > 0 && index1 == 1){\r\n");
      out.write("\t\tdocument.getElementById('Delete').style.visibility='visible';\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tdocument.getElementById('lr4').style.visibility='visible';\r\n");
      out.write("\t\tdocument.getElementById('r4').style.visibility='visible';\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validateform4(){\r\n");
      out.write("\tvar index = document.getElementById(\"r4\").selectedIndex;\r\n");
      out.write("\tvar index1 = document.getElementById(\"r8\").selectedIndex;\r\n");
      out.write("\tif(index > 0 && index1 == 2){\r\n");
      out.write("\t\tdocument.getElementById('update').style.visibility='visible';\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form method=\"POST\" action=\"finalAdminReport\">\r\n");
      out.write("<br><input type=\"text\" readonly=\"readonly\" name=\"username\" id=\"username\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" style =\"background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\" >\r\n");
      out.write("\r\n");
      out.write("       <h1>Report Results</h1>\r\n");
      out.write("        <table width=\"page\" align=\"center\" >\r\n");
      out.write("            <!-- column headers -->\r\n");
      out.write("            <tr>\r\n");
      out.write("                ");
      if (_jspx_meth_core_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </tr>\r\n");
      out.write("            <!-- column data -->\r\n");
      out.write("            ");
      if (_jspx_meth_core_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr8\" style=\"color:#ffffff;font-size:24px;\" >Award Selection</label> </td>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t <td>\r\n");
      out.write(" \t\t\t\t\t    <select name=\"r8\" id=\"r8\" onchange=\"validateform()\">  \r\n");
      out.write("\t\t\t\t\t        <OPTION  value=\"-1\" label=\"--Select--\" selected=\"selected\">  </OPTION>\r\n");
      out.write("\t\t\t\t\t        <OPTION  value=\"Delete\"> Delete </OPTION>\r\n");
      out.write("\t\t\t\t\t        <OPTION  value=\"Update\"> Update </OPTION>  \r\n");
      out.write("\t\t\t\t\t    </select> \r\n");
      out.write("\t\t\t\t\t    </td>   \r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t\r\n");
      out.write("            <tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr1\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Enter Sender Serial ID</label> </td>\r\n");
      out.write("             \t\t <td align=\"center\"> <input id=\"r1\" name=\"r1\" onchange=\"validateform1()\" type=\"text\" style =\"visibility:hidden;background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\t <tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr2\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Enter Reciever Serial ID</label> </td>\r\n");
      out.write("             \t\t <td align=\"center\"> <input id=\"r2\" name=\"r2\" onchange=\"validateform2()\" type=\"text\" style =\"visibility:hidden;background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\t <tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr3\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Award Existing Selection</label> </td>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t <td>\r\n");
      out.write(" \t\t\t\t\t    <select name=\"r3\" id=\"r3\" onchange=\"validateform3()\" style=\"visibility:hidden;\">  \r\n");
      out.write("\t\t\t\t\t        <OPTION  value=\"-1\" label=\"--Select--\" selected=\"selected\">  \r\n");
      out.write("\t\t\t\t\t        ");
      if (_jspx_meth_core_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("\t\t\t\t\t    </select> \r\n");
      out.write("\t\t\t\t\t    </td>   \r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t <td height=\"40\" align=\"center\"> <label id=\"lr4\" style=\"color:#ffffff;font-size:24px;visibility:hidden;\" >Award New Selection</label> </td>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t <td>\r\n");
      out.write(" \t\t\t\t\t    <select name=\"r4\" id=\"r4\" onchange=\"validateform4()\" style=\"visibility:hidden;\">  \r\n");
      out.write("\t\t\t\t\t        <OPTION  value=\"-1\" label=\"--Select--\" selected=\"selected\">  \r\n");
      out.write("\t\t\t\t\t        ");
      if (_jspx_meth_core_005fforEach_005f4(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("\t\t\t\t\t    </select> \r\n");
      out.write("\t\t\t\t\t    </td>   \r\n");
      out.write(" \t\t\t</tr>\r\n");
      out.write(" \t\t\t\r\n");
      out.write("            <tr>\r\n");
      out.write("         \t<td align=\"center\"><input type=\"submit\" name=\"sub\" id=\"Delete\" value=\"Delete\" style=\"visibility:hidden;background-color: #2e466e; color: #ffff; border-radius: 10px;border:6px solid #1f2f47;border-radius:29px;padding:16px 57px;text-shadow:0px 1px 0px #263666;font-size:20px;\">\r\n");
      out.write("\t\t\t<td align=\"center\"><input type=\"submit\" name=\"sub\" id=\"update\" value=\"update\" style=\"visibility:hidden;background-color: #2e466e; color: #ffff; border-radius: 10px;border:6px solid #1f2f47;border-radius:29px;padding:16px 57px;text-shadow:0px 1px 0px #263666;font-size:20px;\">\r\n");
      out.write("\t\t\t</tr>\t \r\n");
      out.write("        </table>\r\n");
      out.write("        </form>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_core_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_core_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_core_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_core_005fforEach_005f0.setParent(null);
    // /finalAdminReport.jsp(95,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f0.setVar("columnName");
    // /finalAdminReport.jsp(95,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/finalAdminReport.jsp(95,16) '${colNames}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${colNames}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_core_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_core_005fforEach_005f0 = _jspx_th_core_005fforEach_005f0.doStartTag();
      if (_jspx_eval_core_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <th>");
          if (_jspx_meth_core_005fout_005f0(_jspx_th_core_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_core_005fforEach_005f0))
            return true;
          out.write("</th>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_core_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_core_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_core_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_core_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_core_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_core_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_core_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_core_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_core_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fforEach_005f0);
    // /finalAdminReport.jsp(96,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${columnName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_core_005fout_005f0 = _jspx_th_core_005fout_005f0.doStartTag();
    if (_jspx_th_core_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_core_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_core_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_core_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_core_005fforEach_005f1.setParent(null);
    // /finalAdminReport.jsp(100,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f1.setVar("row");
    // /finalAdminReport.jsp(100,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/finalAdminReport.jsp(100,12) '${resultReport}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${resultReport}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_core_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_core_005fforEach_005f1 = _jspx_th_core_005fforEach_005f1.doStartTag();
      if (_jspx_eval_core_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <tr>\r\n");
          out.write("                    ");
          if (_jspx_meth_core_005fforEach_005f2(_jspx_th_core_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_core_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("                </tr>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_core_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_core_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_core_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_core_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_core_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fforEach_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_core_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_core_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_core_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_core_005fforEach_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fforEach_005f1);
    // /finalAdminReport.jsp(102,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f2.setVar("column");
    // /finalAdminReport.jsp(102,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/finalAdminReport.jsp(102,20) '${row}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${row}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_core_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_core_005fforEach_005f2 = _jspx_th_core_005fforEach_005f2.doStartTag();
      if (_jspx_eval_core_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                         <td>");
          if (_jspx_meth_core_005fout_005f1(_jspx_th_core_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_core_005fforEach_005f2))
            return true;
          out.write("</td>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_core_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_core_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_core_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_core_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_core_005fforEach_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_core_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_core_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_core_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_core_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fforEach_005f2);
    // /finalAdminReport.jsp(103,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${column}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_core_005fout_005f1 = _jspx_th_core_005fout_005f1.doStartTag();
    if (_jspx_th_core_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_core_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_core_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_core_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_core_005fforEach_005f3.setParent(null);
    // /finalAdminReport.jsp(138,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/finalAdminReport.jsp(138,13) '${sessionScope.aawardname}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.aawardname}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /finalAdminReport.jsp(138,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f3.setVar("dt");
    // /finalAdminReport.jsp(138,13) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f3.setVarStatus("status");
    int[] _jspx_push_body_count_core_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_core_005fforEach_005f3 = _jspx_th_core_005fforEach_005f3.doStartTag();
      if (_jspx_eval_core_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \r\n");
          out.write("\t\t\t\t\t            <option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option> \r\n");
          out.write("\t\t\t\t\t        ");
          int evalDoAfterBody = _jspx_th_core_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_core_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_core_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_core_005fforEach_005f3.doFinally();
      _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_core_005fforEach_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fforEach_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_core_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_core_005fforEach_005f4.setPageContext(_jspx_page_context);
    _jspx_th_core_005fforEach_005f4.setParent(null);
    // /finalAdminReport.jsp(152,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f4.setItems(new org.apache.jasper.el.JspValueExpression("/finalAdminReport.jsp(152,13) '${sessionScope.aawardname}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.aawardname}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /finalAdminReport.jsp(152,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f4.setVar("dt");
    // /finalAdminReport.jsp(152,13) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f4.setVarStatus("status");
    int[] _jspx_push_body_count_core_005fforEach_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_core_005fforEach_005f4 = _jspx_th_core_005fforEach_005f4.doStartTag();
      if (_jspx_eval_core_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \r\n");
          out.write("\t\t\t\t\t            <option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option> \r\n");
          out.write("\t\t\t\t\t        ");
          int evalDoAfterBody = _jspx_th_core_005fforEach_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_core_005fforEach_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_core_005fforEach_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_core_005fforEach_005f4.doFinally();
      _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_core_005fforEach_005f4);
    }
    return false;
  }
}
