/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2014-05-04 06:32:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Retention_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Retention Older Awards</title>\r\n");
      out.write("<link href=\"more.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function checkDate(varBirthDate) {\r\n");
      out.write("\r\n");
      out.write("            var month = varBirthDate.substring(0, 2);\r\n");
      out.write("            var date = varBirthDate.substring(3, 5);\r\n");
      out.write("            var year = varBirthDate.substring(6, 10);\r\n");
      out.write("\r\n");
      out.write("\t\t\tif(parseInt(month) < 1 || parseInt(month) > 12){\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t}else if(parseInt(date) < 1 || parseInt(date) > 31){\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t}else if(parseInt(year) < 1900 || parseInt(year) > 2014){\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("            var myDate = new Date(year, month - 1, date);\r\n");
      out.write("            var today = new Date();\r\n");
      out.write("\t\t\tvar date = new Date();\r\n");
      out.write("\t\t\tvar intYear = date.getFullYear() - 1;\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t     if (myDate > today || parseInt(year) >= intYear) {\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("                return true;\r\n");
      out.write("            }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function validateform1() {\r\n");
      out.write("\t\tvar varBirthDate = /^(\\d{2,2})(\\/)(\\d{2,2})\\2(\\d{4}|\\d{4})$/;\r\n");
      out.write("\t\tif(!(varBirthDate.test(document.getElementById(\"r1\").value) && checkDate(document.getElementById(\"r1\").value)))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Please enter a valid birth date MM/DD/YYYY and Date Not Greater Than Today. Atleast One year Older Date\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"r1\").select();\r\n");
      out.write("\t\t\tdocument.getElementById(\"r1\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar r=confirm(\"Confirmation : Are you sure you want to delete click ok and click Delete Button\");\r\n");
      out.write("\t\tif (r==true)\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t\t  \tdocument.getElementById('Delete').style.visibility='visible';\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t\t  \talert(\"You have cancelled Deletion\");\r\n");
      out.write("\t\t  } \r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\t\r\n");
      out.write("<form method=\"POST\" action=\"Retention\">\r\n");
      out.write("<br><input type=\"text\" readonly=\"readonly\" name=\"username\" id=\"username\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" style =\"background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\" >\r\n");
      out.write("\r\n");
      out.write("  <table width=\"page\" align=\"center\" >\r\n");
      out.write("  \r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t  <td height=\"40\" align=\"center\"> <label style=\"color:#ffffff;font-size:24px\" >Please Enter Date in MM/YY/DDDD</label> </td>\r\n");
      out.write("             \t\t\t <td align=\"center\"> <input id=\"r1\" name=\"r1\" type=\"text\"  onchange=\"validateform1()\" style =\"background: #33CC99; height:55px; width: 600px;text-align:right;font-size:35px; border-radius: 2em; border:6px solid #339999;border-radius:29px; color: #fff; padding-left: 1.5em; outline: none; box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%)\"/></td>\r\n");
      out.write(" \t\t\t\t\t</tr>\r\n");
      out.write("  \t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\"><input type=\"submit\"  id=\"Delete\" name=\"Delete\" value=\"Delete\" style=\"visibility:hidden;background-color: #2e466e; color: #ffff; border-radius: 10px;border:6px solid #1f2f47;border-radius:29px;padding:16px 57px;text-shadow:0px 1px 0px #263666;font-size:20px;\">\r\n");
      out.write("\t\t\t\t\t</tr>\t  \r\n");
      out.write(" </table>\r\n");
      out.write(" </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
